import math
TNT = 4.184 * (10 ** 9)
Energy1 = math.pow(10, ((1.5 * 1.0) +4.8))
Energy2 = math.pow(10, ((1.5 * 5.0) +4.8))
Energy3 = math.pow(10, ((1.5 * 9.1) +4.8))
Energy4 = math.pow(10, ((1.5 * 9.2) +4.8))
Energy5 = math.pow(10, ((1.5 * 9.5) +4.8))
print(f'Ritcher \t  Joules \t\t\t\t\t TNT')
print(f'1.0 \t {Energy1} \t\t\t  {(Energy1 / TNT)}')
print(f'5.0 \t {Energy2} \t\t    {(Energy2 / TNT)}')
print(f'9.1 \t {Energy3} \t  {(Energy3 / TNT)}')
print(f'9.2 \t {Energy4} \t  {(Energy4 / TNT)}')
print(f'9.5 \t {Energy5}  {(Energy5 / TNT)}')
Ritcher_scaleinput =float(input('Please enter a Richter scale value: '))
Energy = math.pow(10, ((1.5 * Ritcher_scaleinput) +4.8))
Total_Tnt = (Energy / TNT)
print(f'Ritcher scale: {Ritcher_scaleinput}')
print(f'Equivalence in joules: {Energy}')
print(f'Equivalence in tons of TNT: {Total_Tnt}')